apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      serviceAccountName: auth-service-sa
      containers:
        - name: auth-service
          image: noureddine078/tcf-auth-service:1
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: "5001"
            - name: NODE_ENV
              value: "production"
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "tcf_prep_db"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: JWT_SECRET
            - name: JWT_EXPIRE
              value: "7d"
            - name: ALLOWED_ORIGINS
              value: "http://tcf-prep.local"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - name: http
      port: 5001
      targetPort: 5001
  type: ClusterIP
